### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Freshwood**
Hey,
I just created a graphical user interace to create a sprite font.
Maybe you can review that and put it to the master branch.
The workflow is the same as before ->
* When the user run the MakeSpriteFont.exe -"" with params then the console gets started (like before)

* When the user just run the MakeSpriteFont.exe without parameters then he can work with the gui.

*Info: I don't touch the previous implemented workflow!*

PS: *Why there is still a cla-required label here?*

Regards,
Freshwood
[Release.zip](https://github.com/Microsoft/DirectXTK/files/241334/Release.zip)

### CODE REVIEW

**Comment by walbourn** [comment]
Follow the link provide by the pull bot: [https://cla.microsoft.com](https://cla.microsoft.com).

**Comment by walbourn** [comment]
Note that I can't seem to build your changes:

    error MSB3552: Resource file "Properties\Resources.resx" cannot be found.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by walbourn** [comment]
I'm  looking at adding some new options to ``MakeSpriteFont``, so you should probably wait a week before resubmitting an updated pull request. Thanks!

**Comment by Freshwood** [comment]
Sry, I was too fast on submitting a new pull request ;).

Yep a good idea.
Later I can review the changes on that tool and can work on the GUI features, so the user has the possibility to use the features on a GUI application, too. 

Regards,

Freshwood

**Pull request closed without merging**
